apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrum-ui
  labels:
    app: scrum-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrum-ui
  template:
    metadata:
      labels:
        app: scrum-ui
    spec:
      containers:
      - name: scrum-ui
        image: vikashashoke/scrum-board_scrum-ui
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: scrum-ui
spec:
  selector:
    app: scrum-ui
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
    #nodePort: 30000


# minikube service mongo-express-service
