apiVersion: v1
kind: Secret
metadata:
        name: postgresdb-secret
type: Opaque
data:
   postgresdb-root-username: c2NydW0=         
   postgresdb-root-password: c2NydW0=
   


#echo -n 'username'| base64
#echo -n 'password'| base64
